package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/deis/workflow-manager/pkg/swagger/models"
)

// CreateClusterDetailsForV2Reader is a Reader for the CreateClusterDetailsForV2 structure.
type CreateClusterDetailsForV2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *CreateClusterDetailsForV2Reader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateClusterDetailsForV2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreateClusterDetailsForV2Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewCreateClusterDetailsForV2OK creates a CreateClusterDetailsForV2OK with default headers values
func NewCreateClusterDetailsForV2OK() *CreateClusterDetailsForV2OK {
	return &CreateClusterDetailsForV2OK{}
}

/*CreateClusterDetailsForV2OK handles this case with default header values.

clusters details response
*/
type CreateClusterDetailsForV2OK struct {
	Payload *models.Cluster
}

func (o *CreateClusterDetailsForV2OK) Error() string {
	return fmt.Sprintf("[POST /v2/clusters/{id}][%d] createClusterDetailsForV2OK  %+v", 200, o.Payload)
}

func (o *CreateClusterDetailsForV2OK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Cluster)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateClusterDetailsForV2Default creates a CreateClusterDetailsForV2Default with default headers values
func NewCreateClusterDetailsForV2Default(code int) *CreateClusterDetailsForV2Default {
	return &CreateClusterDetailsForV2Default{
		_statusCode: code,
	}
}

/*CreateClusterDetailsForV2Default handles this case with default header values.

unexpected error
*/
type CreateClusterDetailsForV2Default struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the create cluster details for v2 default response
func (o *CreateClusterDetailsForV2Default) Code() int {
	return o._statusCode
}

func (o *CreateClusterDetailsForV2Default) Error() string {
	return fmt.Sprintf("[POST /v2/clusters/{id}][%d] createClusterDetailsForV2 default  %+v", o._statusCode, o.Payload)
}

func (o *CreateClusterDetailsForV2Default) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
