package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/deis/workflow-manager/pkg/swagger/models"
)

// NewCreateClusterDetailsParams creates a new CreateClusterDetailsParams object
// with the default values initialized.
func NewCreateClusterDetailsParams() *CreateClusterDetailsParams {
	var ()
	return &CreateClusterDetailsParams{}
}

/*CreateClusterDetailsParams contains all the parameters to send to the API endpoint
for the create cluster details operation typically these are written to a http.Request
*/
type CreateClusterDetailsParams struct {

	/*Body*/
	Body *models.ClusterDetail
}

// WithBody adds the body to the create cluster details params
func (o *CreateClusterDetailsParams) WithBody(body *models.ClusterDetail) *CreateClusterDetailsParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *CreateClusterDetailsParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.ClusterDetail)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
