package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/deis/workflow-manager/pkg/swagger/models"
)

// CreateClusterDetailsReader is a Reader for the CreateClusterDetails structure.
type CreateClusterDetailsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *CreateClusterDetailsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateClusterDetailsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCreateClusterDetailsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewCreateClusterDetailsOK creates a CreateClusterDetailsOK with default headers values
func NewCreateClusterDetailsOK() *CreateClusterDetailsOK {
	return &CreateClusterDetailsOK{}
}

/*CreateClusterDetailsOK handles this case with default header values.

clusters details response
*/
type CreateClusterDetailsOK struct {
	Payload *models.ClusterDetail
}

func (o *CreateClusterDetailsOK) Error() string {
	return fmt.Sprintf("[POST /clusters][%d] createClusterDetailsOK  %+v", 200, o.Payload)
}

func (o *CreateClusterDetailsOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ClusterDetail)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateClusterDetailsDefault creates a CreateClusterDetailsDefault with default headers values
func NewCreateClusterDetailsDefault(code int) *CreateClusterDetailsDefault {
	return &CreateClusterDetailsDefault{
		_statusCode: code,
	}
}

/*CreateClusterDetailsDefault handles this case with default header values.

unexpected error
*/
type CreateClusterDetailsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the create cluster details default response
func (o *CreateClusterDetailsDefault) Code() int {
	return o._statusCode
}

func (o *CreateClusterDetailsDefault) Error() string {
	return fmt.Sprintf("[POST /clusters][%d] createClusterDetails default  %+v", o._statusCode, o.Payload)
}

func (o *CreateClusterDetailsDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
