package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit"
	"github.com/go-swagger/go-swagger/httpkit/validate"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/deis/workflow-manager/pkg/swagger/models"
)

// GetComponentByNameReader is a Reader for the GetComponentByName structure.
type GetComponentByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetComponentByNameReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetComponentByNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetComponentByNameDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetComponentByNameOK creates a GetComponentByNameOK with default headers values
func NewGetComponentByNameOK() *GetComponentByNameOK {
	return &GetComponentByNameOK{}
}

/*GetComponentByNameOK handles this case with default header values.

component releases response
*/
type GetComponentByNameOK struct {
	Payload GetComponentByNameOKBodyBody
}

func (o *GetComponentByNameOK) Error() string {
	return fmt.Sprintf("[GET /versions/{train}/{component}][%d] getComponentByNameOK  %+v", 200, o.Payload)
}

func (o *GetComponentByNameOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetComponentByNameDefault creates a GetComponentByNameDefault with default headers values
func NewGetComponentByNameDefault(code int) *GetComponentByNameDefault {
	return &GetComponentByNameDefault{
		_statusCode: code,
	}
}

/*GetComponentByNameDefault handles this case with default header values.

unexpected error
*/
type GetComponentByNameDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get component by name default response
func (o *GetComponentByNameDefault) Code() int {
	return o._statusCode
}

func (o *GetComponentByNameDefault) Error() string {
	return fmt.Sprintf("[GET /versions/{train}/{component}][%d] getComponentByName default  %+v", o._statusCode, o.Payload)
}

func (o *GetComponentByNameDefault) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*GetComponentByNameOKBodyBody get component by name o k body body

swagger:model GetComponentByNameOKBodyBody
*/
type GetComponentByNameOKBodyBody struct {

	/* data

	Required: true
	*/
	Data []*models.ComponentDetail `json:"data"`
}

// Validate validates this get component by name o k body body
func (o *GetComponentByNameOKBodyBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetComponentByNameOKBodyBody) validateData(formats strfmt.Registry) error {

	if err := validate.Required("getComponentByNameOK"+"."+"data", "body", o.Data); err != nil {
		return err
	}

	for i := 0; i < len(o.Data); i++ {

		if o.Data[i] != nil {

			if err := o.Data[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}
