package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetComponentsByLatestReleaseParams creates a new GetComponentsByLatestReleaseParams object
// with the default values initialized.
func NewGetComponentsByLatestReleaseParams() *GetComponentsByLatestReleaseParams {
	var ()
	return &GetComponentsByLatestReleaseParams{}
}

/*GetComponentsByLatestReleaseParams contains all the parameters to send to the API endpoint
for the get components by latest release operation typically these are written to a http.Request
*/
type GetComponentsByLatestReleaseParams struct {

	/*Body*/
	Body GetComponentsByLatestReleaseBody
}

// WithBody adds the body to the get components by latest release params
func (o *GetComponentsByLatestReleaseParams) WithBody(body GetComponentsByLatestReleaseBody) *GetComponentsByLatestReleaseParams {
	o.Body = body
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetComponentsByLatestReleaseParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
