package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetComponentByNameParams creates a new GetComponentByNameParams object
// with the default values initialized.
func NewGetComponentByNameParams() *GetComponentByNameParams {
	var ()
	return &GetComponentByNameParams{}
}

/*GetComponentByNameParams contains all the parameters to send to the API endpoint
for the get component by name operation typically these are written to a http.Request
*/
type GetComponentByNameParams struct {

	/*Component
	  A component is a single deis component, e.g., deis-router

	*/
	Component string
	/*Train
	  A train is a release cadence type, e.g., "beta" or "stable"

	*/
	Train string
}

// WithComponent adds the component to the get component by name params
func (o *GetComponentByNameParams) WithComponent(component string) *GetComponentByNameParams {
	o.Component = component
	return o
}

// WithTrain adds the train to the get component by name params
func (o *GetComponentByNameParams) WithTrain(train string) *GetComponentByNameParams {
	o.Train = train
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetComponentByNameParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param component
	if err := r.SetPathParam("component", o.Component); err != nil {
		return err
	}

	// path param train
	if err := r.SetPathParam("train", o.Train); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
