package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetDoctorInfoParams creates a new GetDoctorInfoParams object
// with the default values initialized.
func NewGetDoctorInfoParams() *GetDoctorInfoParams {
	var ()
	return &GetDoctorInfoParams{}
}

/*GetDoctorInfoParams contains all the parameters to send to the API endpoint
for the get doctor info operation typically these are written to a http.Request
*/
type GetDoctorInfoParams struct {

	/*UUID
	  A universal Id to represent a sepcific request or report

	*/
	UUID string
}

// WithUUID adds the uuid to the get doctor info params
func (o *GetDoctorInfoParams) WithUUID(uuid string) *GetDoctorInfoParams {
	o.UUID = uuid
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetDoctorInfoParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
