package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/deis/workflow-manager/pkg/swagger/models"
)

// NewPublishComponentReleaseParams creates a new PublishComponentReleaseParams object
// with the default values initialized.
func NewPublishComponentReleaseParams() *PublishComponentReleaseParams {
	var ()
	return &PublishComponentReleaseParams{}
}

/*PublishComponentReleaseParams contains all the parameters to send to the API endpoint
for the publish component release operation typically these are written to a http.Request
*/
type PublishComponentReleaseParams struct {

	/*Body*/
	Body *models.ComponentVersion
	/*Component
	  A component is a single deis component, e.g., deis-router

	*/
	Component string
	/*Release
	  The release version of the deis component, eg., 2.0.0-beta2

	*/
	Release string
	/*Train
	  A train is a release cadence type, e.g., "beta" or "stable"

	*/
	Train string
}

// WithBody adds the body to the publish component release params
func (o *PublishComponentReleaseParams) WithBody(body *models.ComponentVersion) *PublishComponentReleaseParams {
	o.Body = body
	return o
}

// WithComponent adds the component to the publish component release params
func (o *PublishComponentReleaseParams) WithComponent(component string) *PublishComponentReleaseParams {
	o.Component = component
	return o
}

// WithRelease adds the release to the publish component release params
func (o *PublishComponentReleaseParams) WithRelease(release string) *PublishComponentReleaseParams {
	o.Release = release
	return o
}

// WithTrain adds the train to the publish component release params
func (o *PublishComponentReleaseParams) WithTrain(train string) *PublishComponentReleaseParams {
	o.Train = train
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PublishComponentReleaseParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Body == nil {
		o.Body = new(models.ComponentVersion)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param component
	if err := r.SetPathParam("component", o.Component); err != nil {
		return err
	}

	// path param release
	if err := r.SetPathParam("release", o.Release); err != nil {
		return err
	}

	// path param train
	if err := r.SetPathParam("train", o.Train); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
