package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*ComponentVersion component version

swagger:model componentVersion
*/
type ComponentVersion struct {

	/* component
	 */
	Component *Component `json:"component,omitempty"`

	/* update available
	 */
	UpdateAvailable *string `json:"updateAvailable,omitempty"`

	/* version
	 */
	Version *Version `json:"version,omitempty"`
}

// Validate validates this component version
func (m *ComponentVersion) Validate(formats strfmt.Registry) error {
	return nil
}
