package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*ComponentDetail component detail

swagger:model componentDetail
*/
type ComponentDetail struct {

	/* component
	 */
	Component *Component `json:"component,omitempty"`

	/* version
	 */
	Version *Version `json:"version,omitempty"`
}

// Validate validates this component detail
func (m *ComponentDetail) Validate(formats strfmt.Registry) error {
	return nil
}
