package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
)

/*DoctorInfo doctor info

swagger:model doctorInfo
*/
type DoctorInfo struct {

	/* cluster

	Required: true
	*/
	Cluster *Cluster `json:"cluster"`
}

// Validate validates this doctor info
func (m *DoctorInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCluster(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DoctorInfo) validateCluster(formats strfmt.Registry) error {

	if m.Cluster != nil {

		if err := m.Cluster.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}
